# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_name',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
