# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160321_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=400)),
                ('reviewer', models.CharField(max_length=50)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Movie')),
            ],
        ),
    ]
