# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim1', models.CharField(max_length=80)),
                ('sim2', models.CharField(max_length=80)),
                ('sim3', models.CharField(max_length=80)),
                ('sim4', models.CharField(max_length=80)),
                ('sim5', models.CharField(max_length=80)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
    ]
