# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160322_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='movie_name',
        ),
    ]
