# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160322_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(default='imdb', max_length=200),
            preserve_default=False,
        ),
    ]
