# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('director', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=400)),
                ('reviewer', models.CharField(max_length=50)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Movie')),
            ],
        ),
    ]
